### ISSUE TITLE
Allow copying

### ISSUE THREAD

**Issue by freeman42x** [atom-haskell/ide-haskell-repl#59] opened 2018-01-31 08:48 UTC
Would it be possible to change the plugin so that it is possible to copy from the past output?

Thank you

**Comment by lierdakil** [comment] 2018-01-31 11:29
Whoops, that isn't by design. Should be fixed in v0.7.11.

**Closed as completed** 2018-02-02 15:08 UTC

**Comment by freeman42x** [comment] 2018-02-02 18:44
Thank you very much, that was very fast :)
